services:
  - type: web
    name: rweet-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn TweetBlog.wsgi:application"
    envVars:
      - fromGroup: rweet-env
